### ISSUE TITLE
Changing pin does not work due to 4 digit placeholder

### ISSUE THREAD

**Issue by bmml1** [LN-Zap/zap-android#183]
## Description

When trying to reset connection settings or changing the pin in settings a 4 digit empty pin placeholder appears and connection settings can not be resetted / pin can not be changed

## Expected Behavior

6 digit pin placeholder should appear

## Actual Behavior

4 digit pin placeholder appears

## Steps to Reproduce

1. Open app and unlock by entering 6 digit pin
2. Go to settings and push change pin in security section
3. 4 digit placeholder appears

## Your Environment

- Zap version: 0.2.11-alpha
- Android version: Android 10 (LineageOS)
- Device: OnePlus3
- LND Version: 0.92

**Comment by michaelWuensch** [comment]
Thanks for your report. I just tested it and same behavior on my phone. Probably missed to test this with longer PINs.
I will fix this asap!

**Comment by michaelWuensch** [comment]
I have just made a PR to fix this.
Due to our update cycles and store review waiting times it will still take a few weeks until this makes it into an official release, I guess.
In the meantime if you want to get rid of your PIN now, you have to clear the App data or uninstall Zap and then reconnect.

**Comment by michaelWuensch** [comment]
Fix has been released in v0.3.1-beta
