### ISSUE TITLE
Cannot connect to my raspiblitz after setting up a new one 

### ISSUE THREAD

**Issue by Lace79** [LN-Zap/zap-android#196]
1. had already a working setup:
Raspiblitz 1.4 - Zap wallet connected --> working fine! - great App btw - thx for everything

2. had to reset my raspiblitz with lnd Backup - incl. new IP of the raspi

3. after raspiblitz setup:
- raspiblitz 1.5
- deleted the Zap-Wallet on my android device 
- new install from playstore and tried to connect to my raspi, but its not working - i don´t get a connection: 

![grafik](https://user-images.githubusercontent.com/48889296/83947993-c4a53980-a81a-11ea-938b-6835a1010138.png)

i tried to port forward - on my firste setup, everthing already worked without and i don´t need a connection from the internet

what about the certificate ? how can i create a new / delete the old one?

Enviornment: 

raspiblitz 1.5 - home network 

- Zap version:  0.3.0-beta - download 
- Android version: 10
- Device: OnePlus6
- LND Version:  0.10.0-beta

**Comment by michaelWuensch** [comment]
Hi Lace79

While I am personally still at LND v0.9.2-beta (Raspiblitz 1.4), I also have access to a 0.10.0-beta test node with my Zap Android 0.3.0-beta on Android 10. 
This means the LND version cannot be the problem. 

Have you had a look over there yet?
https://docs.zaphq.io/docs-desktop-lnd-configure
It also explains how to recreate the certificate.
Maybe restoring your raspiblitz restored your old tlsextraip, but you now have a new IP. That would mean the certificate might still have the old ip and has to be recreated.

**Comment by Lace79** [comment]
Hi Michael,

thanks for help!

> Maybe restoring your raspiblitz restored your old tlsextraip, but you now have a new IP. That would mean the certificate might still have the old ip and has to be recreated.

I thought the same 

i tried to find the lnd.conf file, but i found more than one 
but i no one of them was the old "Raspiv1.4 IP" - 

Could you pls tell me the path, to find the lnd.conf

**Comment by michaelWuensch** [comment]
@Lace79 
the tlsextraip is not the IP of your Raspi, it has to be the IP of the device from which you are trying to connect from.
In the raspiblitz menu choose the one at the bottom that gives you console access. Then use 
sudo nano /mnt/hdd/lnd/lnd.conf
to edit the lnd conf file.

Look for tlsextraip and set it to your phones IP.
You can add more than one, just duplicate the line if you want to have access from additional devices.

After that go back to the raspiblitz menu and the choose LNDCREDS->RESET
Then you have to redo the connection process with Zap in order to get that new certificate to Zap.

Hope that helps!

**Comment by Lace79** [comment]
Hi Michael,
thank you so much. 
Reset the LNDCREDS was the key - now its working!
