### ISSUE TITLE
Adress copied to clipboard

### ISSUE THREAD

**Issue by ErwanLetard** [LN-Zap/zap-android#28]
Hey, First thank you for your amazing app !
Currently testing it and noticed a small issue. 
When you copy a payment request to your clipboard it add "lightning: ...." in front of it and this generates errors on automatic payment requests (lightning roulette for ex)
Is that removable ?

**Comment by michaelWuensch** [comment]
Hi Erwan,
thanks for reporting.
It can of course be removed, but I am not sure if we actually should do it. In other cases it is desired to have "lightning: ..." in front in order to work as URI Scheme.
I think the ideal solution would be that lightning roulette adds support for lightning invoices with and without "lightning:" in front.

Other opinions?

**Comment by ErwanLetard** [comment]
100% agree. Not sure how this is "usually" done. 
I will contact lightning roulette, see if they can add "lightning" as an optional chain in front of the request. 
Thank you
