### ISSUE TITLE
QR reader should support http links

### ISSUE THREAD

**Issue by dipunm** [LN-Zap/zap-android#362]
## Description
In light of how some will show their receipts, being able to follow a http link may be necessary.

## Context
An example is McDonalds in El Salvador. They provide a QR code which takes you to a site which provides the LN QR code.

**Comment by michaelWuensch** [comment]
Thanks for your suggestion @dipunm !
Can you please describe why apps like Zap should support this flow?
It sounds counterintuitive to me to support a flow that makes it necessary to scan 2 QR Codes instead of one.
What is the benefit for the user in this flow and what is the benefit for the company in this flow?
If there are no benefits then McDonalds should change their flow.

**Comment by dipunm** [comment]
It's an interesting conundrum. If you support this, then the wallet gets a bit more complicated but is also more user friendly. If you don't, then people may work around it, or may look for an alternative app that does support it.

I've seen this work on Breez wallet, it tells you "hey this is a website, click here to visit it.". That's a good UX IMO.

McDonalds in El Salvador isn't changing this setup, wallets are adapting instead as far as I know. It really depends on how strict you want to be against potential bloat. I personally think the trade off is worth it here.

**Comment by michaelWuensch** [comment]
Hi, thanks again for your suggestions!
I have now added this functionality in this PR #399.
This will be in the next release.
