### ISSUE TITLE
Provide details on failed connection

### ISSUE THREAD

**Issue by Kixunil** [LN-Zap/zap-android#37]
Problem
-----------

It's very hard to determine the cause of failed connection.

Steps to reproduce
-------------------------

1. Generate a QR code with e.g. non-existing server, invalid port etc
2. Use the QR code to connect to the node
3. Observe error message

Expected behavior
------------------------

Error message with information on what exactly failed. I'd expect one of these messages:

* Connection refused
* Network unreachable
* Invalid certificate
* Invalid macaroon
* Bad protocol

What happens
-------------------

Just plain "Unable to connect to LND" message.

**Comment by michaelWuensch** [comment]
Hi,
Thanks for your input. Ease of use is one of the main priorities for Zap and the current message is definetly not very helpful. 
Right now I am on a biking trip for two weeks without any access to a computer...
But when I am back, this will be one of the first things I will work on.

**Comment by michaelWuensch** [comment]
The error messages are much more detailed now and will be in the next release.
On connecting with a QR-Code the lndconnect string is tested for validity in means of syntax and general plausibility, but not if the macaroon for example is actually giving you the permission.
At this stage the following errors can be thrown: ( they are more descirptive, I just shortended them here)
- invalid host or port
- invalid syntax
- no macaroon
- invalid certificate (happens if the provided data can not be used to create a certificate)
- invalid macaroon (happens if invalid characters are used and it can not be decoded)

If this validity check is passed, the connection info is safed.
Zap then tries to connect. If it fails, it will show one of the following errors, including possible solutions: (again shortened here)
- Timeout. Server not responding.
- Access denied, invalid macaroon. 
- Unavailable (happens e.g. if server is online, but lnd is not running or on port forwarding problems)

Furthermore Zap Android is now able to unlock a wallet. Before this update a locked wallet would have also caused the standard "Unable to connect to LND" message to show.

**Comment by michaelWuensch** [comment]
The new version is out! Hope this helps :)
