### ISSUE TITLE
Unable to connect node on Android Q Beta 4

### ISSUE THREAD

**Issue by sasquatchmuscle** [LN-Zap/zap-android#39]
When I try to connect the Android Zap (0.2.2-alpha) app to my desktop node using the QR code and paste method I am "unable to connect to LND".  I am on Android Q Beta 4 so I am suspecting this is probably the issue.  

Love the work.

**Comment by michaelWuensch** [comment]
Hi, thanks for the report.
I don't think Android Q beta 4 is causing the problem.
There could be different reasons for this.
For example:

- your LND Wallet has a password and is locked (right now you have to unlock the wallet manually from outside Zap Android.)

- your router blocks communication on port 10009. For example if everything is set up correctly and normally works, I still experience the same error message on some wifis, as they block it.
If that would be the case on your setup, you would have to setup port forwarding for your router.

- testnet seems to have problems right now.
I myself can't connect to my testnet node right now, while mainnet works.

- your certificate could have expired

I will work on better error messages as soon as I can, so problems like this will be easier to find.

Thanks for taking the time to test the app!

**Comment by michaelWuensch** [comment]
The error messages are much more detailed now and will be in the next release.
On connecting with a QR-Code the lndconnect string is tested for validity in means of syntax and general plausibility, but not if the macaroon for example is actually giving you the permission.
At this stage the following errors can be thrown: ( they are more descirptive, I just shortended them here)
- invalid host or port
- invalid syntax
- no macaroon
- invalid certificate (happens if the provided data can not be used to create a certificate)
- invalid macaroon (happens if invalid characters are used and it can not be decoded)

If this validity check is passed, the connection info is safed.
Zap then tries to connect. If it fails, it will show one of the following errors, including possible solutions: (again shortened here)
- Timeout. Server not responding.
- Access denied, invalid macaroon. 
- Unavailable (happens e.g. if server is online, but lnd is not running or on port forwarding problems)

Furthermore Zap Android is now able to unlock a wallet. Before this update a locked wallet would have also caused the standard "Unable to connect to LND" message to show.

**Comment by michaelWuensch** [comment]
The new version is live. 
Can update to 0.2.3-alpha and see if you get it to work / what error message is displayed?

**Comment by sasquatchmuscle** [comment]
Still receiving this error.  It asks to connect to host then shows the following error.  Is there issues with being on pierres node launcher vs a nodl or casa? 

![lnzap android error](https://user-images.githubusercontent.com/48186094/61166678-13f1c580-a4f7-11e9-829b-b364b97651a3.png)

**Comment by JimmyMow** [comment]
@sasquatchmuscle if you are running the Node Launcher I assume you are running it on your home network. You'll need to make sure you are port forwarding and that LND is accessible from wherever you're trying to access it

**Comment by michaelWuensch** [comment]
Hi, 
As you closed it, I think you figured it out. Nice! 
Can you very short tell what was the problem / solution, so I can help others if they have this issue as well?

**Comment by sasquatchmuscle** [comment]
I updated zap on android and it was the port forwarding issue.  All set, thanks for the help!
