### ISSUE TITLE
Zap changes the final invoice amount in BTC when switching between sats and dollars.

### ISSUE THREAD

**Issue by Relaxo143** [LN-Zap/zap-android#92]
[video_2019-09-04_19-06-18.zip](https://github.com/LN-Zap/zap-android/files/3575491/video_2019-09-04_19-06-18.zip)

- Zap version: 0.2.4-alpha
- Device: Samsung Galaxy S8
- LND Version: 0.7.1-beta

**Comment by maraph** [comment]
Hey @Relaxo143 ,

happy to hear from you again! 
Thanks for the report and the awesome video! 🎉 
You are right, this should not happen.

We will investigate and give you an update on the progress. 🔍

**Comment by michaelWuensch** [comment]
Hey @Relaxo143 

Thanks for report and the video!
I am aware of this behaviour but thought this is not a big deal.
When paying an invoice, you will notice this does not happen. The reason is here we have a fixed amount of satoshis I can refer to.

When making an own invoice, right now it just converts and rounds the values each time you swich the unit.
But you are right should not be that way. We will fix this!

**Comment by Relaxo143** [comment]
> Hey @Relaxo143
> 
> Thanks for report and the video!
> I am aware of this behaviour but thought this is not a big deal.
> When paying an invoice, you will notice this does not happen. The reason is here we have a fixed amount of satoshis I can refer to.
> 
> When making an own invoice, right now it just converts and rounds the values each time you swich the unit.
> But you are right should not be that way. We will fix this!

Thanks for this. If you could include the newest translations and longer invoice expiry times in the patch it would be perfect!

**Comment by michaelWuensch** [comment]
Fixed in 0.2.6
